version: '3.3'

services:
  app:
    image: python:3.11.6
    volumes:
      - .:/app
    ports:
      - 8004:8000
    command: bash -c "pip install poetry && cd app && poetry install && poetry run uvicorn server_seabattle.app:app --host 0.0.0.0 --port 8000"
